export { default as Contacto } from './Contacto'
export { default as Destacados } from './Destacados'
export { default as Detalle } from './Detalle'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound'